version: '3'

services:
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 159
      POSTGRES_DB: django_pet
    ports:
      - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: davewalker777@yandex.ru
      PGADMIN_DEFAULT_PASSWORD: 159
    ports:
      - "5050:80"
    depends_on:
      - db

  web:
    build: .
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - C:/Users/mrsch/PycharmProjects/somedjango/taskmanager:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
volumes:
  postgres_data: